# ── Namespace ──────────────────────────────────────────────
apiVersion: v1
kind: Namespace
metadata:
  name: traffic
---
# ── Database PV + PVC ──────────────────────────────────────
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: traffic
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/tvs-data/database
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: traffic
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# ── Evidence PV + PVC ──────────────────────────────────────
apiVersion: v1
kind: PersistentVolume
metadata:
  name: evidence-pv
  namespace: traffic
spec:
  storageClassName: ""
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/tvs-data/outputs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: evidence-pvc
  namespace: traffic
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
# ── Models PV + PVC ────────────────────────────────────────
apiVersion: v1
kind: PersistentVolume
metadata:
  name: models-pv
  namespace: traffic
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/tvs-data/models
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: traffic
spec:
  storageClassName: ""
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

# do this first      
# mkdir -p /home/ubuntu/tvs-data/database
# mkdir -p /home/ubuntu/tvs-data/outputs
# mkdir -p /home/ubuntu/tvs-data/models

# Copy your models in
# cp ~/traffic_Devops/models/* /home/ubuntu/tvs-data/models/
